updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "Actions"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
    
version: 2